/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OrganizationProfilesRouteImport } from './routes/organization-profiles'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations/$orgId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationProfilesRoute = OrganizationProfilesRouteImport.update({
  id: '/organization-profiles',
  path: '/organization-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => OrganizationsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/organization-profiles': typeof OrganizationProfilesRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/organization-profiles': typeof OrganizationProfilesRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/organization-profiles': typeof OrganizationProfilesRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/login'
    | '/organization-profiles'
    | '/organizations'
    | '/roles'
    | '/settings'
    | '/users'
    | '/auth/callback'
    | '/organizations/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/login'
    | '/organization-profiles'
    | '/organizations'
    | '/roles'
    | '/settings'
    | '/users'
    | '/auth/callback'
    | '/organizations/$orgId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/login'
    | '/organization-profiles'
    | '/organizations'
    | '/roles'
    | '/settings'
    | '/users'
    | '/auth/callback'
    | '/organizations/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  LoginRoute: typeof LoginRoute
  OrganizationProfilesRoute: typeof OrganizationProfilesRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-profiles': {
      id: '/organization-profiles'
      path: '/organization-profiles'
      fullPath: '/organization-profiles'
      preLoaderRoute: typeof OrganizationProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganizationsRouteChildren {
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  LoginRoute: LoginRoute,
  OrganizationProfilesRoute: OrganizationProfilesRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
